{
 "title": "Smart disk data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host: ",
    "query": "label_values(smartctl_physical_disk_powerOnHours, instance)"
   },
   {
    "name": "diskID",
    "label": "Disk",
    "query": "label_values(smartctl_physical_disk_powerOnHours{instance=~\"$instance:9633\"}, diskID)"
   },
   {
    "name": "LName",
    "label": "Array",
    "query": "label_values(ssacli_logical_array_cylinders, LName)"
   }
  ]
 },
 "panels": [
  { "title": "Logical Array", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ssacli_logical_array_cylinders{instance=~\"$instance:9633\", LName=~\"$LName\"}"
    }
   ]
  },
  {
   "title": "Array Cylinder",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ssacli_logical_array_cylinders{instance=~\"$instance:9633\", LName=~\"$LName\"}",
     "legendFormat": "{{LName}}"
    }
   ]
  },
  { "title": "Raid Card Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ssacli_hw_raid_controller_slot{instance=~\"$instance:9633\"}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ssacli_hw_raid_controller_cacheSize{instance=~\"$instance:9633\"} - ssacli_hw_raid_controller_available_cacheSize{instance=~\"$instance:9633\"}",
     "legendFormat": "Use Cache"
    },
    {
     "expr": "ssacli_hw_raid_controller_cacheSize{instance=~\"$instance:9633\"}",
     "legendFormat": "Total Cache"
    }
   ]
  },
  {
   "title": "Controller Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ssacli_hw_raid_controller_temperature{instance=~\"$instance:9633\"}"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ssacli_hw_raid_controller_temperature_battery{instance=~\"$instance:9633\"}"
    }
   ]
  },
  {
   "title": "Cache Modul Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ssacli_hw_raid_controller_temperature_cacheModule{instance=~\"$instance:9633\"}"
    }
   ]
  },
  { "title": "Disk Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "ssacli_physical_disk_curTemp{instance=~\"$instance:9633\"}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sum(ssacli_physical_disk_curTemp{instance=~\"$instance:9633\", diskID=~\"$diskID\"}) by (diskID)",
     "legendFormat": "Cur temp Disk: {{diskID}}"
    }
   ]
  },
  {
   "title": "Disk Lifetime",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 30 },
   "targets": [
    {
     "expr": "sum(smartctl_physical_disk_powerOnHours{instance=~\"$instance:9633\", diskID=~\"$diskID\"}) by (diskID, model)"
    },
    {
     "expr": "sum(smartctl_physical_disk_powerCycleCount{instance=~\"$instance:9633\", diskID=~\"$diskID\"}) by (diskID)"
    }
   ]
  },
  {
   "title": "Disk Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartctl_physical_disk_endToEndError{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "End-to-End: {{diskID}}"
    },
    {
     "expr": "smartctl_physical_disk_offlineUncorrectable{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Offline Unrec: {{diskID}}"
    },
    {
     "expr": "smartctl_physical_disk_rawReadErrorRate{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Raw Read: {{diskID}}"
    },
    {
     "expr": "smartctl_physical_disk_runtimeBadBlock{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Bad Block: {{diskID}}"
    },
    {
     "expr": "smartctl_physical_disk_reportedUncorrect{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Uncorrect: {{diskID}}"
    },
    {
     "expr": "smartctl_physical_disk_uDMACRCErrorCount{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "DMACRC: {{diskID}}"
    }
   ]
  },
  {
   "title": "Realocated Stat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartctl_physical_disk_reallocatedEventCount{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Event: {{diskID}}"
    },
    {
     "expr": "smartctl_physical_disk_reallocatedSectorCt{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Sector: {{diskID}}"
    }
   ]
  },
  {
   "title": "Comand Timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartctl_physical_disk_commandTimeout{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "{{diskID}}"
    }
   ]
  },
  {
   "title": " Sector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartctl_physical_disk_currentPendingSector{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Pending: {{diskID}}"
    },
    {
     "expr": "smartctl_physical_disk_unusedRsvdBlkCntTot{instance=~\"$instance:9633\", diskID=~\"$diskID\"}",
     "legendFormat": "Unused Reserved: {{diskID}}"
    }
   ]
  }
 ]
}